const ADD_MOVIES = "ADD_MOVIES";
const EDIT_MOVIES = "EDIT_MOVIES";
const DELETE_MOVIE = "DELETE_MOVIE";
const SEE_DETAIL = "SEE_DETAIL";

export { ADD_MOVIES, EDIT_MOVIES, DELETE_MOVIE, SEE_DETAIL };